import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import BlogCard from "../components/BlogCard/BlogCard";
import { Header } from "../components/Header/Header";
import { IpfsFileUpload } from "../components/IpfsFileUpload/IpfsFileUpload";
import Toggle from "../context/ThemeToggle";
import { network } from "../config/wallets";
const Home: NextPage = () => {
  const [feedData, setfeedData] = useState([]);

  useEffect(() => {
    console.log({ network });

    const fetchData = async () => {
      const data = await axios.get(
        "https://random-data-api.com/api/company/random_company?size=30"
      );

      console.log({ data });

      setfeedData(data.data);
    };
    fetchData();
  }, [network]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="px-0">
     

        <div className="flex flex-wrap justify-evenly">
          
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
          <BlogCard />
        </div>

    
      </div>


    </div>
  );
};

export default Home;
